<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class StaffDeptSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('staff_depts')->insert([
            // Departemen hasil hutan
            // Sruktur Organisasi
            [
                'id_kategoristaff' => 3,
                'id_divisi' => 5,
                'foto' => 'foto_staffdept/Istie.jpg',
                'nama' => 'Dr. Istie Sekartining Rahayu, S.Hut., M.Si',
                'tanggal_lahir' => '1974-04-22',
                'nip' => '197404222005012001',
                'jabatan' => 'Ketua Departemen Hasil Hutan',
                'email' => 'istiesr@apps.ipb.ac.id',
                'password' => Hash::make('istie123'),
                'username' => 'istie',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 3,
                'id_divisi' => 5,
                'foto' => 'foto_staffdept/Irsan.jpg',
                'nama' => 'Dr. Irsan Alipraja,  S.Hut., M.Si.',
                'tanggal_lahir' => '1987-11-22',
                'nip' => '198711222014041001',
                'jabatan' => 'Sekretaris Departemen Hasil Hutan',
                'email' => 'alipraja.thh42@apps.ipb.ac.id',
                'password' => Hash::make('irsan123'),
                'username' => 'irsan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 3,
                'id_divisi' => 5,
                'foto' => 'foto_staffdept/Wayan.png',
                'nama' => 'Prof. Dr. Ir. I Wayan Darmawan, M.Sc.',
                'tanggal_lahir' => '1966-02-12',
                'nip' => '196602121991031002',
                'jabatan' => 'Kepala PS S2 dan PS S3 ITHH',
                'email' => 'w_darmawan@apps.ipb.ac.id',
                'password' => Hash::make('wayan123'),
                'username' => 'wayan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 3,
                'id_divisi' => 5,
                'foto' => 'foto_staffdept/Trisna.jpg',
                'nama' => 'Prof. Dr. Ir. Trisna Priadi, M. Eng. Sc',
                'tanggal_lahir' => '1967-04-25',
                'nip' => '196704251993021001',
                'jabatan' => 'Kepala Pendidikan dan PL',
                'email' => 'trisnapr@apps.ipb.ac.id',
                'password' => Hash::make('trisna123'),
                'username' => 'trisna',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 3,
                'id_divisi' => 1,
                'foto' => 'foto_staffdept/Mahdi.jpg',
                'nama' => 'Dr. Mahdi Mubarok, S.Si., M.Si',
                'tanggal_lahir' => '1983-12-30',
                'nip' => '198312302010121008',
                'jabatan' => 'Komisi Kemahasiswaan, AKPI',
                'email' => 'mahdi@apps.ipb.ac.id',
                'password' => Hash::make('mahdi123'),
                'username' => 'mahdi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 3,
                'id_divisi' => 2,
                'foto' => 'foto_staffdept/Nyoman.jpg',
                'nama' => 'Prof. Dr. Ir. I Nyoman Jaya Wistara, M.S.',
                'tanggal_lahir' => '1963-12-31',
                'nip' => '196312311989031027',
                'jabatan' => 'Kepala Divisi biorefinery Hasil Hutan',
                'email' => 'nwistara@apps.ipb.ac.id',
                'password' => Hash::make('nyoman123'),
                'username' => 'nyoman',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 3,
                'id_divisi' => 4,
                'foto' => 'foto_staffdept/Karlina.jpg',
                'nama' => 'Prof. Dr. Lina Karlinasari, S.Hut, M.Sc.F.trop',
                'tanggal_lahir' => '1973-11-26',
                'nip' => '197311261998022001',
                'jabatan' => 'Kepala Divisi Rekayasa dan Desain Bangunan Kayu',
                'email' => 'karlinasari@apps.ipb.ac.id',
                'password' => Hash::make('karlina123'),
                'username' => 'karlina',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 3,
                'id_divisi' => 1,
                'foto' => 'foto_staffdept/Dede.jpg',
                'nama' => 'Prof. Dr. Ir. Dede Hermawan, M. Sc.',
                'tanggal_lahir' => '1963-07-11',
                'nip' => '196307111991031002',
                'jabatan' => 'Kepala Divisi Biokomposit',
                'email' => 'dedehe@apps.ipb.ac.id',
                'password' => Hash::make('dede123'),
                'username' => 'dede',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 3,
                'id_divisi' => 5,
                'foto' => 'foto_staffdept/Imam.jpg',
                'nama' => 'Prof. Dr. Ir. Imam Wahyudi, M.S.',
                'tanggal_lahir' => '1963-01-06',
                'nip' => '196301061987031004',
                'jabatan' => 'Kepala Divisi Teknologi Peningkatan Mutu Kayu',
                'email' => 'imamwa@apps.ipb.ac.id',
                'password' => Hash::make('imam123'),
                'username' => 'imam',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 3,
                'id_divisi' => 3,
                'foto' => 'foto_staffdept/Bintang.jpg',
                'nama' => 'Ir. Bintang C.H  Siamngunsong, M.S., PhD',
                'tanggal_lahir' => '1963-04-13',
                'nip' => '196304131987031004',
                'jabatan' => 'Kepala Divisi Manajemen Industri Hasil Hutan',
                'email' => 'bintangdhh@apps.ipb.ac.id',
                'password' => Hash::make('bintang123'),
                'username' => 'bintang',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Tenaga Pendidik/Dosen
            [
                'id_kategoristaff' => 1,
                'id_divisi' => 2,
                'foto' => 'foto_staffdept/Deded.jpg',
                'nama' => 'Prof. Dr. Ir. Deded Sarip Nawawi, M.Sc.F.Trop',
                'tanggal_lahir' => '1966-01-13',
                'nip' => '196601131991031001',
                'jabatan' => 'Guru Besar',
                'email' => 'dsnawawi@apps.ipb.ac.id',
                'password' => Hash::make('deded123'),
                'username' => 'deded',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 1,
                'id_divisi' => 4,
                'foto' => 'foto_staffdept/Nares.jpg',
                'nama' => 'Prof. Dr.Ir. Naresworo Nugroho, M.Si',
                'tanggal_lahir' => '1965-01-22',
                'nip' => '196501221989031002 ',
                'jabatan' => 'Guru Besar',
                'email' => 'nares@apps.ipb.ac.id',
                'password' => Hash::make('nares123'),
                'username' => 'nares',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 1,
                'id_divisi' => 2,
                'foto' => 'foto_staffdept/Rita.jpg',
                'nama' => 'Dr. Ir. Rita Kartika Sari, M.S.',
                'tanggal_lahir' => '1968-11-24',
                'nip' => '196811241995122001 ',
                'jabatan' => 'Lektor Kepala',
                'email' => 'rita_kartikasari@apps.ipb.ac.id',
                'password' => Hash::make('rita123'),
                'username' => 'rita',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 1,
                'id_divisi' => 3,
                'foto' => 'foto_staffdept/Togu.jpg',
                'nama' => 'Dr. Ir. Elisa Ganda Togu Manurung, M.S.',
                'tanggal_lahir' => '1962-11-07',
                'nip' => '196211071987031001 ',
                'jabatan' => 'Asisten Ahli',
                'email' => 'toguman@apps.ipb.ac.id',
                'password' => Hash::make('togu123'),
                'username' => 'togu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 1,
                'id_divisi' => 5,
                'foto' => 'foto_staffdept/Arinana.jpg',
                'nama' => 'Dr. Arinana, S.Hut, M.Si',
                'tanggal_lahir' => '1974-01-01',
                'nip' => '197401012006042014 ',
                'jabatan' => 'Lektor Kepala',
                'email' => 'arinana@apps.ipb.ac.id',
                'password' => Hash::make('arinana123'),
                'username' => 'arinana',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 1,
                'id_divisi' => 2,
                'foto' => 'foto_staffdept/Anne.jpg',
                'nama' => 'Anne Carolina, S.Si., M.Si',
                'tanggal_lahir' => '1981-09-24',
                'nip' => '198109242009122004 ',
                'jabatan' => 'Lektor',
                'email' => 'a_caroline@apps.ipb.ac.id',
                'password' => Hash::make('anne123'),
                'username' => 'anne',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 1,
                'id_divisi' => 4,
                'foto' => 'foto_staffdept/Fengky.jpg',
                'nama' => 'Dr. Fengky Satria Yoresta, S.T., M.T',
                'tanggal_lahir' => '1987-06-10',
                'nip' => '1987061020101210005',
                'jabatan' => 'Lektor',
                'email' => 'syfengky@apps.ipb.ac.id',
                'password' => Hash::make('fengky123'),
                'username' => 'fengky',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 1,
                'id_divisi' => 1,
                'foto' => 'foto_staffdept/Lukman.jpg',
                'nama' => 'Lukmanul Hakim Zaini, S.Hut., M.Sc.',
                'tanggal_lahir' => '1986-07-31',
                'nip' => '198607312015041001',
                'jabatan' => 'Lektor',
                'email' => 'lukmanhz@apps.ipb.ac.id',
                'password' => Hash::make('lukman123'),
                'username' => 'lukman',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 1,
                'id_divisi' => 3,
                'foto' => 'foto_staffdept/Vera.jpg',
                'nama' => 'Vera Junita Br Sitanggang, S.Hut., M.Si',
                'tanggal_lahir' => '1987-06-30',
                'nip' => '198706302015042002',
                'jabatan' => 'Asisten Ahli',
                'email' => 'vera-junita@apps.ipb.ac.id',
                'password' => Hash::make('vera123'),
                'username' => 'vera',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 1,
                'id_divisi' => 5,
                'foto' => 'foto_staffdept/Miftah.jpeg',
                'nama' => 'M. Miftah Rahman, S.Hut., M.Si',
                'tanggal_lahir' => '1994-02-07',
                'nip' => '199402072020121004',
                'jabatan' => 'Asisten Ahli',
                'email' => 'miftahrahman@apps.ipb.ac.id',
                'password' => Hash::make('miftah123'),
                'username' => 'miftah',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 1,
                'id_divisi' => 2,
                'foto' => 'foto_staffdept/Yanico.jpg',
                'nama' => 'Dr. Yanico Hadi Prayogo, M.Si.',
                'tanggal_lahir' => null,
                'nip' => '199501062024061001',
                'jabatan' => 'Calon Dosen ',
                'email' => 'yanicopryg@apps.ipb.ac.id',
                'password' => Hash::make('yanico123'),
                'username' => 'yanico',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Tenaga kependidikan
            [
                'id_kategoristaff' => 2,
                'id_divisi' => null,
                'foto' => 'foto_staffdept/Anto.jpg',
                'nama' => 'Anto Gustanto, S.P.',
                'tanggal_lahir' => null,
                'nip' => '197708052009101001',
                'jabatan' => 'Kepala Tata Usaha',
                'email' => null,
                'password' => Hash::make('anto123'),
                'username' => 'anto',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 2,
                'id_divisi' => null,
                'foto' => 'foto_staffdept/Lina.jpg',
                'nama' => 'Lina Meliantina',
                'tanggal_lahir' => null,
                'nip' => '197105201993032001',
                'jabatan' => 'Kemahasiswaan',
                'email' => null,
                'password' => Hash::make('lina123'),
                'username' => 'lina',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 2,
                'id_divisi' => null,
                'foto' => 'foto_staffdept/Esti.jpg',
                'nama' => 'Esti Prihatini, S.Si., M.Si.',
                'tanggal_lahir' => null,
                'nip' => '197512162000032006',
                'jabatan' => 'Laboran Teknologi Peningkatan Mutu Kayu',
                'email' => null,
                'password' => Hash::make('esti123'),
                'username' => 'esti',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 2,
                'id_divisi' => null,
                'foto' => 'foto_staffdept/Irfan.jpg',
                'nama' => 'Muhamad Irfan',
                'tanggal_lahir' => null,
                'nip' => '198006052008101002',
                'jabatan' => 'Laboran Rekayasa dan Desain Bangunan Kayu',
                'email' => null,
                'password' => Hash::make('irfan123'),
                'username' => 'irfan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 2,
                'id_divisi' => null,
                'foto' => 'foto_staffdept/Junawan.jpg',
                'nama' => 'Junawan Supriadi',
                'tanggal_lahir' => null,
                'nip' => '3201300501800005',
                'jabatan' => 'Laboran Kimia Hasil Hutan',
                'email' => null,
                'password' => Hash::make('junawan123'),
                'username' => 'junawan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 2,
                'id_divisi' => null,
                'foto' => 'foto_staffdept/Lastri.jpg',
                'nama' => 'Sulastri',
                'tanggal_lahir' => null,
                'nip' => '3201306405790003',
                'jabatan' => 'Administrasi Pendidikan',
                'email' => null,
                'password' => Hash::make('lastri123'),
                'username' => 'lastri',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 2,
                'id_divisi' => null,
                'foto' => 'foto_staffdept/Kikin.jpg',
                'nama' => 'Kikin Mutaqin',
                'tanggal_lahir' => null,
                'nip' => '3201381307850001',
                'jabatan' => 'Kepegawaian',
                'email' => null,
                'password' => Hash::make('kikin123'),
                'username' => 'kikin',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 2,
                'id_divisi' => null,
                'foto' => 'foto_staffdept/Bunga.jpg',
                'nama' => 'Siti Bunga Utami, S.Ak.',
                'tanggal_lahir' => null,
                'nip' => '3201305611910001',
                'jabatan' => 'PUMK',
                'email' => null,
                'password' => Hash::make('bunga123'),
                'username' => 'bunga',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 2,
                'id_divisi' => null,
                'foto' => 'foto_staffdept/Gilang.jpg',
                'nama' => 'Gilang Dwi Laksono, S.Hut.',
                'tanggal_lahir' => null,
                'nip' => '3271041011960020',
                'jabatan' => 'Laboran Teknologi Peningkatan Mutu Kayu',
                'email' => null,
                'password' => Hash::make('gilang123'),
                'username' => 'gilang',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 2,
                'id_divisi' => null,
                'foto' => 'foto_staffdept/Yenah.jpg',
                'nama' => 'Yenah',
                'tanggal_lahir' => null,
                'nip' => '3271045303770015',
                'jabatan' => 'Pramu Kantor',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 2,
                'id_divisi' => null,
                'foto' => 'foto_staffdept/Suwandi.jpg',
                'nama' => 'Suwandi',
                'tanggal_lahir' => null,
                'nip' => '3201302007820009',
                'jabatan' => 'Pramu Kantor',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => 2,
                'id_divisi' => null,
                'foto' => 'foto_staffdept/Yusep.jpg',
                'nama' => 'Muhamad Yusep',
                'tanggal_lahir' => null,
                'nip' => '3201301201880005',
                'jabatan' => 'Laboran Teknologi Peningkatan Mutu Kayu',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Departemen Manajemen Hasil Hutan
            // Tenaga Pendidik/Dosen
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof.Dr.Ir. Elias',
                'tanggal_lahir' => null,
                'nip' => '195609021981031003',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof.Dr.Ir. I Nengah Surati Jaya, M.Agr.',
                'tanggal_lahir' => null,
                'nip' => '196109091986011001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof.Dr. Ir. Bramasto Nugroho, M.S.',
                'tanggal_lahir' => null,
                'nip' => '195811041987031005',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof.Dr.Ir. Hardjanto, M.S',
                'tanggal_lahir' => null,
                'nip' => '195506061981031008',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof.Dr.Ir. Didik Suharjito, M.S.',
                'tanggal_lahir' => null,
                'nip' => '196304011994031001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof.Dr.Ir. Heri Purnomo, M.Comp.',
                'tanggal_lahir' => null,
                'nip' => '196404211988031002',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof.Dr.Ir. Juang Rata Matangaran, M.S.',
                'tanggal_lahir' => null,
                'nip' => '196312211988031001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof.Dr.Ir. Dodik Ridho Nurrochmat, M.Sc.Forest.Trop',
                'tanggal_lahir' => null,
                'nip' => '197003291996081001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof.Dr.Ir. Sudarsono Soedomo, M.S., MPPA',
                'tanggal_lahir' => null,
                'nip' => '195608251980031019',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof.Dr.Ir. Muhamad Buce Saleh, M.S.',
                'tanggal_lahir' => null,
                'nip' => '195710051983031002',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof.Dr. Efi Yuliati Yovi, S.Hut.M.Life.Env.Sc.',
                'tanggal_lahir' => null,
                'nip' => '197407241999032003',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr.Ir. Iin Ichwandi, M.Sc.Forest.Trop',
                'tanggal_lahir' => null,
                'nip' => '196412171990021001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr.Ir. Hendrayanto, M.Agr.',
                'tanggal_lahir' => null,
                'nip' => '196111261986011001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr.Ir. Ahmad Budiaman, M.Sc.Forest.Trop.',
                'tanggal_lahir' => null,
                'nip' => '196510101990021001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr.Ir. Bahruni, MS',
                'tanggal_lahir' => null,
                'nip' => '196105011988031003',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr.Ir. Muhdin, M.Sc.Forest.Trop',
                'tanggal_lahir' => null,
                'nip' => '196606101991031006',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr.Ir. Leti Sundawati, M.Sc.Forest.Trop.',
                'tanggal_lahir' => null,
                'nip' => '196408301990032001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr. Tatang Tiryana, S.Hut., M.Sc',
                'tanggal_lahir' => null,
                'nip' => '197307271999031002',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr.Ir. Budi Kuncahyo, MS',
                'tanggal_lahir' => null,
                'nip' => '196107201986011001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr.Ir. Teddy Rusolono, MS',
                'tanggal_lahir' => null,
                'nip' => '196210241988031002',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr.Ir. Gunawan Santosa, MS',
                'tanggal_lahir' => null,
                'nip' => '196411021988031002',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dra. Sri Rahaju, Msi',
                'tanggal_lahir' => null,
                'nip' => '196112171990032003',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr.Dra.  Nining Puspaningsih, MSi.',
                'tanggal_lahir' => null,
                'nip' => '196306121990032014',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr. Ujang Suwarna, S.Hut. M.Sc',
                'tanggal_lahir' => null,
                'nip' => '197205121997021001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr Handian Purwawangsa, S.Hut., M.Si',
                'tanggal_lahir' => null,
                'nip' => '197901012005011003',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr. Soni Trison, S.Hut., M.Si',
                'tanggal_lahir' => null,
                'nip' => '197711232007011002',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Priyanto, S.Hut., M.Si.',
                'tanggal_lahir' => null,
                'nip' => '197505082005011003',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Qori Pebrial Ilham, S.Hut., M.Si',
                'tanggal_lahir' => null,
                'nip' => '199002282019031011',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Fitta Setiajati, S.Hut., M.Si',
                'tanggal_lahir' => null,
                'nip' => '199010112019032027',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Tenaga Kependidikan
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Riksawati',
                'tanggal_lahir' => null,
                'nip' => '196905211989022001',
                'jabatan' => 'Tenaga Kependidikan',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Ria Kodariah, S.Si',
                'tanggal_lahir' => null,
                'nip' => '197112262007102001',
                'jabatan' => 'Tenaga Kependidikan',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'M. Hasanudin, A.Md',
                'tanggal_lahir' => null,
                'nip' => '197401062007011001',
                'jabatan' => 'Tenaga Kependidikan',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Meli Sumarni',
                'tanggal_lahir' => null,
                'nip' => '197505062007102001',
                'jabatan' => 'Tenaga Kependidikan',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Uus Saeful Mukarom, S.Hut.',
                'tanggal_lahir' => null,
                'nip' => '197203172007101001',
                'jabatan' => 'Tenaga Kependidikan',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Achmad Fatoni',
                'tanggal_lahir' => null,
                'nip' => '197111292008101002',
                'jabatan' => 'Tenaga Kependidikan',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Saeful Rohim',
                'tanggal_lahir' => null,
                'nip' => '198107052008101002',
                'jabatan' => 'Tenaga Kependidikan',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Supriatna',
                'tanggal_lahir' => null,
                'nip' => '196910182014091004',
                'jabatan' => 'Tenaga Kependidikan',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Linda Zakiah Savitri, S.Hut.',
                'tanggal_lahir' => null,
                'nip' => null,
                'jabatan' => 'Tenaga Kependidikan',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Afiat Febrianyah, S.Komp.',
                'tanggal_lahir' => null,
                'nip' => null,
                'jabatan' => 'Tenaga Kependidikan',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Irsya Muthia Muthmainah, S.Hut.',
                'tanggal_lahir' => null,
                'nip' => null,
                'jabatan' => 'Tenaga Kependidikan',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Jumadi Jayadi',
                'tanggal_lahir' => null,
                'nip' => null,
                'jabatan' => 'Tenaga Kependidikan',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Yeti Mulyawati',
                'tanggal_lahir' => null,
                'nip' => null,
                'jabatan' => 'Tenaga Kependidikan',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Siti Sopiah',
                'tanggal_lahir' => null,
                'nip' => null,
                'jabatan' => 'Tenaga Kependidikan',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Risma Amaliah',
                'tanggal_lahir' => null,
                'nip' => null,
                'jabatan' => 'Tenaga Kependidikan',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Daniel Rachman',
                'tanggal_lahir' => null,
                'nip' => null,
                'jabatan' => 'Tenaga Kependidikan',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Tsanie Ditya Kurnia, S.E',
                'tanggal_lahir' => null,
                'nip' => null,
                'jabatan' => 'Tenaga Kependidikan',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Departemen Silvikultur
            // Tenaga Pendidik/Dosen
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof.Dr.Ir. Cecep Kusmana, MS',
                'tanggal_lahir' => null,
                'nip' => '196102121985011001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof.Dr.Ir. Bambang Hero Saharjo, M.Agr',
                'tanggal_lahir' => null,
                'nip' => '196411101990021001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof.Dr.Ir. Iskandar Z. Siregar, M.For.Sc',
                'tanggal_lahir' => null,
                'nip' => '196603201990021001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof.Dr.Ir. Sri Wilarso Budi R, MS',
                'tanggal_lahir' => null,
                'nip' => '196202101988031003',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof.Dr.Ir. Nurheni Wijayanto, MS',
                'tanggal_lahir' => null,
                'nip' => '196010241984031009',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof.Dr.Ir. Lailan Syaufina, M.Sc',
                'tanggal_lahir' => null,
                'nip' => '196406131989032001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof.Dr.Ir. Noor Farikhah Haneda, M. Si',
                'tanggal_lahir' => null,
                'nip' => '196609211990032001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof.Dr.Ir. Prijanto Pamoengkas, M.Sc.F.Trop',
                'tanggal_lahir' => null,
                'nip' => '196312061989031004',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof.Dr.Ir. Ulfah Juniarti, M.Agr',
                'tanggal_lahir' => null,
                'nip' => '195806061983032001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof.Dr.Ir. Basuki Wasis, M.Si',
                'tanggal_lahir' => null,
                'nip' => '196510021991031003',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof.Dr.Ir. Elis Nina Herliyana, M.Si',
                'tanggal_lahir' => null,
                'nip' => '196704211991032001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr.Ir. Irdika Mansur, M.For.Sc',
                'tanggal_lahir' => null,
                'nip' => '196605231990021001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr.Ir. Istomo, Msi',
                'tanggal_lahir' => null,
                'nip' => '196207061989031003',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr.Ir. Omo Rusdiana, M.Sc.Forest.Trop',
                'tanggal_lahir' => null,
                'nip' => '196301191989031003',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr. Ati Dwi Nurhayati, S.Hut, M.Si',
                'tanggal_lahir' => null,
                'nip' => '197706222007012001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr. Erianto Indra Putra, S.Hut. M.Si',
                'tanggal_lahir' => null,
                'nip' => '197401072005011002',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr.Ir. Arum Sekar Wulandari, MS',
                'tanggal_lahir' => null,
                'nip' => '196603162006042003',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Ir. Andi Sukendro, MSi',
                'tanggal_lahir' => null,
                'nip' => '196205051987031004',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr. Muhammad Alam Firmansyah, S.Hut, MSi',
                'tanggal_lahir' => null,
                'nip' => '197911182007011001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr. Yunik Istikorini, SP,M,P',
                'tanggal_lahir' => null,
                'nip' => '196906021994122001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr. Adisti Permatasari Putri Hartoyo, S.Hut, M.Si',
                'tanggal_lahir' => null,
                'nip' => '199012242015042003',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Fifi Gus Dwiyanti, S.Hut, M.Agr, Ph.D',
                'tanggal_lahir' => null,
                'nip' => '198708152019032012',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Lufthi Rusniarsyah, SP., M.Si',
                'tanggal_lahir' => null,
                'nip' => '198202102014041001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Bayu Winata, S.Hut, M.Si',
                'tanggal_lahir' => null,
                'nip' => '199110102018031001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Departemen Konservasi Sumberdaya Hutan Dan Ekowisata
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Syafitri Hidayati S.Hut., M.Si., Ph.D.',
                'tanggal_lahir' => null,
                'nip' => '198805232019032016',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Fairuz Rafidah Aflaha S.K.Pm., M.S.',
                'tanggal_lahir' => null,
                'nip' => '199505022024062001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr. Ir. Rinekso Soekmadi M.Sc.F.Trop.',
                'tanggal_lahir' => null,
                'nip' => '196406221988031002',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof. Dr. Ir. Lilik Budi Prasetyo M.Sc.',
                'tanggal_lahir' => null,
                'nip' => '196203161988031002',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Ir. Dones Rinaldi M.Sc.F.Trop.',
                'tanggal_lahir' => null,
                'nip' => '196105181988031002',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr. Ir. Yeni Aryati Mulyani M.Sc.',
                'tanggal_lahir' => null,
                'nip' => '196104111987032001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr. Ir. Nyoto Santoso M.S.',
                'tanggal_lahir' => null,
                'nip' => '196203151986031002',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof. Dr. Ir. Burhanuddin Masyud M.S.',
                'tanggal_lahir' => null,
                'nip' => '195811211986031003',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Resti Meilani S.Hut., M.Si.',
                'tanggal_lahir' => null,
                'nip' => '197705142005012001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr. Eva Rachmawati S.Hut., M.Si.',
                'tanggal_lahir' => null,
                'nip' => '197703212005012003',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof. Dr. Ir. Ani Mardiastuti M.Sc.',
                'tanggal_lahir' => null,
                'nip' => '195909251983032002',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof. Dr. Ir. Yanto Santosa D.E.A.',
                'tanggal_lahir' => null,
                'nip' => '196010041985011001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof. Dr. Ir. Ervizal Amzu M.S.',
                'tanggal_lahir' => null,
                'nip' => '195906181985031003',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr. Yudi Setiawan S.P., M.Env.Sc.',
                'tanggal_lahir' => null,
                'nip' => '197807302007101002',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr. Ir. Arzyana Sunkar M.Sc.',
                'tanggal_lahir' => null,
                'nip' => '197102151995122001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Ir. Edhi Sandra M.Si.',
                'tanggal_lahir' => null,
                'nip' => '196610191993031002',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Ir. Siswoyo M.Si.',
                'tanggal_lahir' => null,
                'nip' => '196502081992031003',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr. Ir. Abdul Haris Mustari M.Sc.F.Trop.',
                'tanggal_lahir' => null,
                'nip' => '196510151991031003',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr. Ir. Agus Hikmat M.Sc.F.Trop.',
                'tanggal_lahir' => null,
                'nip' => '196209181989031002',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof. Dr. Ir. Mirza Dikari Kusrini M.Si.',
                'tanggal_lahir' => null,
                'nip' => '196511141990022001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof. Dr. Ir. Ricky Avenzora M.Sc.F.Trop.',
                'tanggal_lahir' => null,
                'nip' => '196406111989031002',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr. Dede Aulia Rahman S.Hut., M.Si.',
                'tanggal_lahir' => null,
                'nip' => '198701142014041001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof. Dr. Ir. Sambas Basuni M.S.',
                'tanggal_lahir' => null,
                'nip' => '195809151984031003',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Ir. Agus Priyono M.S.',
                'tanggal_lahir' => null,
                'nip' => '196108121986011001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Ir. Lin Nuriah Ginoga M.Si.',
                'tanggal_lahir' => null,
                'nip' => '196511161992032001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr. Ir. Siti Badriyah Rushayati M.Si.',
                'tanggal_lahir' => null,
                'nip' => '196507042000032001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr. Ir. Harnios Arief M.Sc.F.Trop.',
                'tanggal_lahir' => null,
                'nip' => '196407091990021002',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr. Ir. Rachmad Hermawan M.Sc.F.Trop.',
                'tanggal_lahir' => null,
                'nip' => '196705041992031004',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Prof. Dr. Ir. Jarwadi Budi Hernowo M.Sc.F.Trop.',
                'tanggal_lahir' => null,
                'nip' => '195811111987031003',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr. Ir. Nandi Kosmaryandi M.Sc.F.Trop.',
                'tanggal_lahir' => null,
                'nip' => '196606281998021001',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Amrina Rosyada S.T.P., M.Agr.Sc.',
                'tanggal_lahir' => null,
                'nip' => '199506112024062003',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Dr. Sutopo, S.Hut, M.Si',
                'tanggal_lahir' => null,
                'nip' => '3201301807830006',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategoristaff' => null,
                'id_divisi' => null,
                'foto' => null,
                'nama' => 'Arif Kurnia Wijayanto, S.TP, M.Sc, P.hD',
                'tanggal_lahir' => null,
                'nip' => '1606072107900002',
                'jabatan' => 'Tenaga Pendidik/Dosen',
                'email' => null,
                'password' => null,
                'username' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
